ALTER TABLE player ALTER COLUMN email DROP NOT NULL;
ALTER TABLE player ALTER COLUMN password DROP NOT NULL;
ALTER TABLE player ADD COLUMN IF NOT EXISTS vk_id int UNIQUE;
ALTER TABLE player ADD COLUMN IF NOT EXISTS vk_token text UNIQUE;